---
- name: Transfer and run script on remote node
  hosts: centos
  tasks:
    - name: Transfer script to remote node
      copy:
        src: /root/ansible/cent20/script.sh  
        dest: /tmp/script.sh          
        mode: 0755                 

    - name: Execute script on remote node
      command: sh /tmp/script.sh        
    - name: Reboot remote node
      command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for the node to reboot
      wait_for_connection:
        timeout: 300
    - name: Display contents of os-release file
      command: cat /etc/os-release
